set -g default-terminal "xterm-256color"
#set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"
# action key
unbind C-b
set-option -g prefix C-t
set-option -g repeat-time 0

# send prefix to client inside window
bind-key -n C-a send-prefix

#### Key bindings

set-window-option -g mode-keys vi

#bind t send-key C-t
# Reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"
# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

#### basic settings

set-option -g status-justify "left"
#set-option utf8-default on
#set-option -g mouse-select-pane
set-window-option -g mode-keys vi
#set-window-option -g utf8 on
# look'n feel - Rose Pine Moon
set-option -g status-fg "#9ccfd8" # Rose Pine foam
set-option -g status-bg "#2a273f" # Rose Pine surface
set -g pane-active-border-style fg="#ea9a97",bg=default # Rose Pine rose
set -g window-style fg="#908caa",bg=default # Rose Pine subtle
set -g window-active-style fg="#3e8fb0",bg=default # Rose Pine pine
set-option -g history-limit 64096

set -sg escape-time 10

#### COLOUR

# default statusbar colors
set-option -g status-style bg="#2a273f",fg="#f6c177",default # Surface, Gold

# default window title colors
set-window-option -g window-status-style fg="#6e6a86",bg="#232136",dim # Muted, Base

# active window title colors
set-window-option -g window-status-current-style fg="#ea9a97",bg=default,bright # Rose

# pane border
set-option -g pane-border-style fg="#2a273f" # Surface
set-option -g pane-active-border-style fg="#f6c177",bg="#2a273f" # Gold, Surface

# message text
set-option -g message-style bg="#2a273f",fg="#ea9a97" # Surface, Rose

# pane number display
set-option -g display-panes-active-colour "#3e8fb0" # Pine
set-option -g display-panes-colour "#ea9a97" # Rose

# clock
set-window-option -g clock-mode-colour "#9ccfd8" # Foam

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

