theme = "tokyonight"

[editor]
line-number = "absolute"
mouse = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
"del" = "delete_selection"
"C-c" = ":clipboard-yank"

[editor.indent-guides]
render = false
character = ""

[keys.normal.space]
"y" = ":clipboard-yank-join" # Join and yank selections to clipboard

[keys.select.space]
"y" = ":clipboard-yank-join" # Join and yank selections to clipboard